### ISSUE TITLE
项目自适应布局 - rem

### ISSUE THREAD

**Issue by jtwang7** [jtwang7/React-Note#13]
# 项目自适应布局 - rem
参考文章：
[【前端适配】vw+rem自适应适配方案](https://zhuanlan.zhihu.com/p/97984007)

## 前言
实现页面布局随窗口缩放自适应宽高变化。rem 布局无需借助js，只用 css 就可以实现一定屏宽范围内元素大小随屏幕改变平稳变化。

## 单位
* em: 相对本身元素 font-size 值计算得到的相对大小（2em 就是 2 倍本元素 font-szie 值大小）
* rem: 相对于根元素（html）的 font-size 值的相对大小
* vw：viewport（页面视口）宽度的 1%
* vh：viewport（页面视口）高度的 1%
* %：相对于父元素的大小
* px：实际像素值

### 单位选取标准
px 设完是个定值，完全无法自适应，首先被排除。
其次，em 因为随着元素的嵌套，这个相对值将随时改变，使代码结构复杂难懂，排除。
rem 既是个相对值，能自适应，又因为其相对根元素的大小，参照物不变，可以贯穿于代码始终。

## 步骤
1. 元素大小单位选用 rem。
2. 根据设计稿的屏幕宽度设置 html 的 `font-size` 大小，且单位用 vw (高度用 vh，后续以 vw 为例)。
3. 通过 `media query` 设置 html 根 `font-size` 的最大最小 px 值。

以 1800px 视口宽度为例：
1800px 宽度的视口，html 的 `font-size` 设为 1vw (`font-size` 计算得到的实际大小为 `1800px / 100 = 18px`)，p 标签设为 1rem ，则为 18px 实际大小。
假设 html 的 `font-size` 设为 3vw (`font-size` 计算得到的实际大小为 `1800px / 100 * 3 = 54px`)，p 标签设为 1rem ，则为 54px 实际大小。
> rem 取决于 html 的 font-size 具体值。由于页面变化 vw 也会发生变化，因此 `font-size` 会根据视口自适应，因此 rem 也会相对应调整。`rem + font-size + vw/vh` 实际就是将自适应的 `font-size` 值变相应用到了全局。

"媒体查询" 主要用于限制视口缩放的区间，并对满足相应区间条件的视口添加对应的样式。

## 媒体查询
[CSS Media Queries](https://www.w3schools.com/css/css3_mediaqueries_ex.asp)
媒体查询是一种向不同设备提供定制样式表的流行技术。
> 即根据不同的屏幕大小，添加或替换不同的 CSS 样式。

语法：
```css
@media [only] screen  and ( css 属性 ) [and ( css 属性)] {
  /* ... css 样式 */
}
```
> 语法语义化理解：
> * `@media` 为固定名，用于指明该属性为媒体查询类型。
> * only 可理解为“只有当...”。
> * screen 指明作用对象为屏幕视口。
> * and 之后跟相应的筛选条件，条件以 CSS 属性组成。

示例 (单条件筛选限制)：
```css
/* Set the background color of body to tan */
body {
  background-color: tan;
}

/* On screens that are 992px or less, set the background color to blue */
@media screen and (max-width: 992px) {
  body {
    background-color: blue;
  }
}

/* On screens that are 600px or less, set the background color to olive */
@media screen and (max-width: 600px) {
  body {
    background-color: olive;
  }
}
```

示例 (多条件筛选限制)：
You can also use the (max-width: ..) and (min-width: ..) values to set a minimum width and a maximum width.
For example, when the browser's width is between 600 and 900px, change the appearance of a <div> element:
```css
@media screen and (max-width: 900px) and (min-width: 600px) {
  div.example {
    font-size: 50px;
    padding: 50px;
    border: 8px solid black;
    background: yellow;
  }
}
```

示例 (根据屏幕方向添加对应样式)
```css
@media only screen and (orientation: landscape) {
  body {
    background-color: lightblue;
  }
}
```
